- apps/svelte.dev/content/docs/svelte/01-introduction/02-getting-started.md
- apps/svelte.dev/content/docs/svelte/03-template-syntax/06-snippet.md
- apps/svelte.dev/content/docs/svelte/07-misc/07-v5-migration-guide.md
- apps/svelte.dev/content/docs/svelte/07-misc/99-faq.md
counterpart to https://github.com/sveltejs/svelte/pull/13789
> make links internal

- apps/svelte.dev/src/routes/tutorial/[...slug]/+page.svelte
fixes #528. we had side-effects in `capture` which is a no-no
> reset scroll to 0 if it wasn't restored

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Try to avoid PRs going to the wrong place like in https://github.com/sveltejs/svelte.dev/pull/543
> Add some basic contributing docs

- packages/repl/src/lib/Repl.svelte
Fixed an issue, that caused hiding the input/output switch on mobiles:
the fix: 
```css
.container {
min-height: 0;
}
```
> By default, the container cannot be smaller than the size of its content.
> Its initial size is set to min-height: auto.
https://github.com/user-attachments/assets/f423a149-5a68-4731-9c97-f36400803053
Simple fix but hope it helps,
ly Rich <33
> fix:playground mobile overflow

- apps/svelte.dev/src/hooks.server.js
I started on https://github.com/sveltejs/svelte.dev/issues/540 and realized it's going to be pretty trick to do it right. This takes care of the FAQ page. The rest are more complicated, so we'll have to handle them separately (see https://github.com/sveltejs/svelte.dev/pull/538/files#r1811559880)
This also alphabetizes the redirects
> fix: redirect faq

- packages/repl/src/lib/workers/bundler/index.ts
using a relative import means it may be relatively imported from within a node module, which leads to wrong results
fixes #555
> fix: ensure shared file is resolved properly in all situations

- apps/learn.svelte.dev/vercel.json
> fix: redirect learn.svelte.dev homepage for svelte.dev/tutorial

- apps/svelte.dev/content/tutorial/03-sveltekit/02-routing/01-pages/index.md
- packages/site-kit/src/lib/markdown/renderer.ts
Our builds got slower because the cache hash was always different. This happened because the dependencies were calculated based on the generated code after Vite compiled it, i.e. it would check stuff in `.svelte-kit/output/server/chunks/...js`. This seems to have worked fine for a while, but now Vite mashes things up such that code from `svelte.dev/src/lib/server/content.ts` is mixed in, which has loads of Vite hashes in it, and so the file content is always different. That in turn means our hash is always different, and so the snippet cache never hits.
The pragmatic solution is to hard-code the path to the original file and add a sanity check to ensure it's still accurate.
> fix: speed up build by ensuring stable cache

- packages/site-kit/src/lib/search/SearchBox.svelte
- packages/site-kit/src/lib/stores/nav.ts
This fixes the layout shift behind cmd+k SearchBox when it is toggled on-off. Words in paragraphs jump and images scale.
- Added `scrollbar-gutter` to the html when `overflow` is `hidden` by the `overlay_open` store. This allows body size to remain stable. 
- Changed body positioning from `fixed` to `absolute` to account for the `scrollbar-gutter`.
- Removed `top` from frozen body to account for the new positioning.
- Added local state to the SearchBox because the last scroll position is not stored in the `top` style declaration of the body anymore.
---
`scrollbar-gutter` is not yet supported in Safari, this means the experience is unchanged for Safari users.
> fix: layout shift behind command+k search

- apps/svelte.dev/content/tutorial/01-svelte/05-events/02-inline-handlers/index.md
In [Basic Svelte / Events / inline handlers](https://svelte.dev/tutorial/svelte/inline-handlers):
Event handler has incorrect argument. Works as is because of (deprecated) `Window.event` (I think).
> chore: Fix argument name in inline event handler

- apps/kit.svelte.dev/vercel.json
closes https://github.com/sveltejs/svelte.dev/issues/581
also removes `permanent` from two redirects that are sub-optimal and can be improved
> fix: improve SvelteKit redirects

- packages/site-kit/src/lib/components/Text.svelte
Snippet `controls` element without the `filename` children overlays the actual snippet code and the first line becomes hard to select and downgrades the UX.
This happens because `controls` div has full width and `z-index: 2` which makes content under it hardly selectable.
Remove the 100% width and make the width auto according to the contents of its children + add the `right: 0` position to be placed in the top right corner. 
This solution works for both types:
- Without filename ![image](https://github.com/user-attachments/assets/91eeec2e-678a-4bbb-bc5d-f54a5ccae11d)
- With filename (width grows automatically) ![image](https://github.com/user-attachments/assets/d0b2130f-8d5a-431e-8baa-6a93c0adfd48)
> docs: remove hidden overlay on snippet controls

- apps/svelte.dev/content/tutorial/01-svelte/05-events/02-inline-handlers/+assets/app-b/src/lib/App.svelte
- Changed event parameter from 'e' to 'event' in onpointermove handler for consistency with instructions.
https://svelte.dev/tutorial/svelte/inline-handlers
> docs: fix pointer move event parameter for consistency

- apps/svelte.dev/src/routes/_home/Testimonials.svelte
fixes #578
worked when I tried it locally with `hover: hover`, so I'm assuming it works for the opposite on mobile
> fix: colorful testimonials for hoverless devices

- packages/site-kit/src/lib/nav/Nav.svelte
Disables scrolling while the nav menu is open. Solves #515, where the bug is better described in-depth. Accomplished by setting the body's `overflow` style to 'hidden' when the menu is open.
> fix: disable nav scroll while menu is open

- apps/svelte.dev/src/routes/_home/Testimonials.svelte
Safari 18 is spectacularly broken. This downgrades the brokenness to 'eww that looks awful' from its previous level of 'are they just trolling us?'
Closes #516 but not really
> sort of fix safari bug, but not really

- apps/svelte.dev/src/routes/docs/+page.svelte
continuing work on https://github.com/sveltejs/svelte.dev/issues/540
> fix: correct redirects from v3 docs

- apps/svelte.dev/src/hooks.server.js
continuing work on https://github.com/sveltejs/svelte.dev/issues/540
It seems I duplicated some existing redirects, but I'm not sure which ones or where they live
https://svelte.dev/docs/svelte-easing already redirects, but https://svelte.dev/docs/typescript doesn't. Any idea where the first redirect lives?
> fix: add more svelte.dev redirects

- apps/svelte.dev/content/tutorial/02-advanced-svelte/05-advanced-transitions/01-deferred-transitions/+assets/app-a/src/lib/App.svelte
There is wrong todo key for description in tutorial.
> fix: typo in deferred-transitions tutorial

- apps/svelte.dev/src/hooks.server.js
This was added for backwards compat, but conflicts with our current redirect
fixes #607
> fix: redirect docs/svelte to overview page

- packages/repl/src/lib/workers/bundler/index.ts
adjusts the regex for this
Fixes #605
> fix: properly resolve packages with version

- apps/svelte.dev/src/routes/tutorial/[...slug]/Controls.svelte
the default grayed-out styling makes it super hard to quickly find what you're looking for. This gives them a black and bold styling, which better fits their use case of separating exercises into sections.
> fix: make tutorial sections more visible

- packages/site-kit/src/lib/components/Text.svelte
first/last pre isn't enough, as there can be nested pre tags due to shiki
Fixes #611
> fix: ensure right code is copied

- apps/svelte.dev/content/tutorial/02-advanced-svelte/05-advanced-transitions/01-deferred-transitions/index.md
on the tutorial page the code snippet for `TodoList.svelte` is:
```svelte
<li
class:done
in:receive={{ key: todo.id }}
out:send={{ key: todo.id }}
>
```
it should look:
```svelte
<li
class:done={todo.done}
in:receive={{ key: todo.id }}
out:send={{ key: todo.id }}
>
```
if copied and pasted, it gives:
`done is not defined in TodoList.svelte in App.svelte`
[link to tutorial page](https://svelte.dev/tutorial/svelte/deferred-transitions)
If this is a documentation PR (i.e. changing content within `apps/svelte.dev/content/docs`), then this is the wrong repository to make those changes. The content in this folder is synced from other repositories. Therefore, these changes should be made in their respective repositories (at https://github.com/sveltejs/svelte or https://github.com/sveltejs/kit, …
> docs:  add {todo.done} to class:done in TodoList.svelte code snippet

- packages/site-kit/src/lib/styles/tokens.css
This avoids switching font if you slightly zoom your browser
> change resolution cut-off

- apps/learn.svelte.dev/vercel.json
closes https://github.com/sveltejs/svelte.dev/issues/619
These may indicate a few possible places to expand tutorial content. I have no idea what `/tutorial/core` was and if it ever actually existed.
Some issues I noted while going through these:
- https://github.com/sveltejs/svelte/issues/13984
- https://github.com/sveltejs/svelte.dev/issues/669
- https://github.com/sveltejs/svelte.dev/issues/670
> fix: update tutorial redirects

- packages/site-kit/src/lib/components/Text.svelte
- packages/site-kit/src/lib/styles/tokens.css
> style: Change bullet points color and position

- apps/svelte.dev/content/blog/2024-10-22-svelte-5-is-alive.md
- apps/svelte.dev/src/lib/server/content.ts
This gives us the ability to pin a blog post to the top of `/blog`. If multiple posts are pinned simultaneously (i.e. they have a `pinnedUntil` in the future), the most recently published wins.
> pin announcement blog post

- packages/site-kit/src/lib/components/Banner.svelte
- packages/site-kit/src/lib/components/Shell.svelte
- packages/site-kit/src/lib/docs/DocsContents.svelte
- packages/site-kit/src/lib/nav/Nav.svelte
- packages/site-kit/src/lib/nav/NavContextMenu.svelte
Initially this was to remove some unwanted dark/light mode transitions left over from long ago, hence the branch name, but In the process I realised that the documentation sidebar menu is broken — between 800px and 832px, the sidebar isn't visible but you also can't access the contents via the menu.
With this PR, we keep the mobile nav up to 832px — we only switch to the desktop nav when there's enough room to show the docs sidebar
> fix menu dead zone

- apps/svelte.dev/content/tutorial/01-svelte/09-transitions/04-custom-css-transitions/index.md
```js
--let visible = true;--
++let visible = $state(true);++
```
> docs: use runes instead of old syntax in `tutorial/custom-css-transitions`

- apps/svelte.dev/src/routes/devtools/updates.json/+server.ts
Originally from https://github.com/sveltejs/svelte-devtools/pull/213
Prerequisite for https://github.com/sveltejs/svelte-devtools/issues/207
> feat: add devtools updates

- apps/svelte.dev/content/tutorial/02-advanced-svelte/02-snippets/03-implicit-snippet-props/index.md
> docs: replace '(' with '{' in snippet tag

- packages/editor/src/lib/Editor.svelte
- packages/editor/src/lib/Workspace.svelte.ts
- packages/repl/src/lib/Output/Output.svelte
- packages/repl/src/lib/Repl.svelte
DRYs some stuff out, moves some stuff out of the effect in `Editor.svelte`. Doing this ahead of tackling #65
> move diagnostics logic into workspace, expose workspace.current_compiled

- packages/editor/src/lib/Workspace.svelte.ts
- packages/repl/src/lib/Output/AstNode.svelte
- packages/repl/src/lib/Output/AstView.svelte
- packages/repl/src/lib/Output/Output.svelte
- packages/site-kit/src/lib/components/Checkbox.svelte
closes #65. there's some UI fixes I'd like to make but those can be follow-ups
> add modern AST toggle

- packages/repl/src/lib/Output/AstNode.svelte
- packages/repl/src/lib/Output/AstView.svelte
Before — bizarre layout, inaccessible to keyboard users, fugly arrows with wonky positioning, blank text for `undefined`, arrays that are expandable even if they have no children, small hit areas that move when items are toggled, weird use of underlining, hard to tell what's inside arrays without clicking into each item, just generally a bit of a clusterfuck
After — none of that. Just way more usable all round.
I actually broke toggling in #692 — oops — and it renders the AST view effectively useless so I'm gonna go ahead and self-merge
> Nicer ast view

- packages/site-kit/src/lib/styles/tokens.css
> shrink font size when georgia is used

- packages/site-kit/src/lib/search/SearchBox.svelte
closes #664. Instead of actively focusing the `<body>` when the search box is closed, just blur whatever the active element is. Has the same effect in terms of [SFNSP](https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation-starting-point), but doesn't cause an unwanted focus ring to appear
> blur active element instead of focusing document

- packages/site-kit/src/lib/components/Text.svelte
- packages/site-kit/src/lib/styles/base.css
- packages/site-kit/src/lib/styles/tokens.css
- make paragraph breaks less spacey
- move `ul` closer to the preceeding paragraph which gives more visual clarity of where it belongs to
- give code blocks a bit more space at the top/bottom on larger screens
- give blockquotes more space at the top/bottom on larger screens
Combined, these changes give more visual clarity of which things belong together, which stand on its own, etc
> chore: spacing tweaks

- packages/site-kit/src/lib/search/SearchBox.svelte
- packages/site-kit/src/lib/search/SearchResultList.svelte
closes #650 — adds a 'clear' button next to the 'close' button, and tidies up the styles a bit
> Tweak search box

- apps/svelte.dev/src/routes/search/+page.server.js
- packages/site-kit/src/lib/search/SearchBox.svelte
- packages/site-kit/src/lib/search/search-worker.ts
- packages/site-kit/src/lib/search/search.ts
- packages/site-kit/src/lib/search/types.d.ts
This implements a better search ranking algorithm. If you're on `/tutorial` and you search for, say, 'transitions', the top results will be from the tutorial. The same search if you're on `/docs` will prioritise docs results. But if you search for something that yields an exact title match, like `sv add`, then that will float to the top regardless of where you are.
The weights are magic numbers and there may be better ones, but these ones seem to work pretty well.
> Better search

- apps/svelte.dev/src/lib/db/client.js
- apps/svelte.dev/src/lib/db/session.js
> allow site to be built without credentials

- apps/svelte.dev/content/tutorial/02-advanced-svelte/01-advanced-reactivity/01-raw-state/index.md
Fixed a minor typo:
Old Statement - "...it's important to main referential equality..."
Fixed Statement - "...it's important to maintain referential equality..."
Tutorial [Link](https://svelte.dev/tutorial/svelte/raw-state)
> docs: Update index.md for Tutorial: Advanced Svelte / Advanced reactivity / Raw state

- apps/svelte.dev/content/tutorial/02-advanced-svelte/04-advanced-bindings/04-dimensions/index.md
> docs: Add note for dimension bindings.

- apps/svelte.dev/src/routes/(authed)/playground/[id]/AppControls.svelte
- packages/repl/src/lib/Input/Migrate.svelte
- packages/site-kit/src/lib/styles/utils/buttons.css
Fixes #434 and improves tooltips in various ways:
- fixes font/padding
- adds `.tooltip` and `.tooltip-left` classes (can add `.tooltip-right` if we discover a need for it) that makes it easy to add a tooltip to any button with an `aria-label`
- shows tooltips when button is focused, not just when it's hovered, making it more useful for sighted users that use keyboard navigation
> better tooltips

- apps/svelte.dev/scripts/sync-docs/index.ts
- apps/svelte.dev/scripts/sync-docs/utils.ts
This improves the sync script a bit — it allows you to specify a `-p` or `--pull` flag which pulls from the remote (or clones the repo if necessary), and also specify which packages we care about:
```bash
pnpm sync-docs          # sync everything
pnpm sync-docs -w       # sync everything and watch for changes
pnpm sync-docs cli      # just sync `cli` docs
pnpm sync-docs cli kit  # sync `cli` and `kit` docs
pnpm sync-docs -pw kit  # pull or clone `kit` docs, sync, and watch for changes
```
This is groundwork for setting up an automated workflow
> add --pull flag to sync-docs, pull existing repo if nec

- .github/workflows/sync-docs.yml
This is not my wheelhouse, so it'll probably take some fiddling to get right, BUT
If it works then we will be able to add corresponding workflows in the source repos that create/update PRs in this repo so that we don't need to manually sync docs any more. Only way we can actually test this is by merging it, so that's what I'll do
> add sync-docs workflow

- apps/svelte.dev/content/tutorial/04-advanced-sveltekit/07-conclusion/01-next-steps/index.md
Replace deprecated `create-svelte` package with new `sv` command in the advanced SvelteKit tutorial conclusion.
> docs(tutorial): update app creation command to Svelte CLI

- apps/svelte.dev/content/docs/svelte/98-reference/30-runtime-warnings.md
copy-paste fail. pretty huge oversight, whoops. will instamerge once green
> fix runtime-warnings page

- .github/workflows/sync-docs.yml
- apps/svelte.dev/scripts/sync-docs/README.md
> add sync-docs README

- apps/svelte.dev/content/blog/2024-11-01-whats-new-in-svelte-november-2024.md
Let me know if I missed anything!
> docs: "What's new in Svelte" November newsletter

- apps/svelte.dev/content/blog/2016-11-26-frameworks-without-the-framework.md
- apps/svelte.dev/content/blog/2017-09-06-the-zen-of-just-writing-css.md
- apps/svelte.dev/content/blog/2019-04-20-write-less-code.md
- apps/svelte.dev/content/blog/2019-04-22-svelte-3-rethinking-reactivity.md
- apps/svelte.dev/content/blog/2022-11-01-whats-new-in-svelte-november-2022.md
- apps/svelte.dev/content/tutorial/01-svelte/02-reactivity/02-deep-state/index.md
- apps/svelte.dev/content/tutorial/02-advanced-svelte/02-snippets/02-passing-snippets/index.md
- apps/svelte.dev/content/tutorial/02-advanced-svelte/05-advanced-transitions/01-deferred-transitions/index.md
- apps/svelte.dev/content/tutorial/03-sveltekit/08-stores/02-navigating-store/index.md
- apps/svelte.dev/content/tutorial/03-sveltekit/09-errors-and-redirects/01-error-basics/index.md
- apps/svelte.dev/content/tutorial/04-advanced-sveltekit/01-hooks/04-handleerror/index.md
- apps/svelte.dev/src/lib/server/renderer.ts
- apps/svelte.dev/src/routes/(authed)/apps/+page.svelte
- apps/svelte.dev/src/routes/blog/+page.svelte
A number of these have snuck in over the years. This adjusts the remaining instances that aren't synced from the Svelte or Kit repos.
> chore: replace non-breaking spaces

- apps/svelte.dev/src/lib/components/Modal.svelte
- apps/svelte.dev/src/lib/components/SecondaryNav.svelte
- apps/svelte.dev/src/routes/(authed)/apps/+page.svelte
- apps/svelte.dev/src/routes/blog/+page.svelte
- apps/svelte.dev/src/routes/docs/+page.svelte
- apps/svelte.dev/src/routes/tutorial/[...slug]/Chrome.svelte
- apps/svelte.dev/src/routes/tutorial/[...slug]/filetree/ContextMenu.svelte
- apps/svelte.dev/src/routes/tutorial/[...slug]/filetree/Item.svelte
- packages/editor/src/lib/codemirror.css
- packages/repl/src/lib/Input/ComponentSelector.svelte
- packages/repl/src/lib/Output/CompilerOptions.svelte
- packages/repl/src/lib/Output/Output.svelte
- packages/repl/src/lib/Output/PaneWithPanel.svelte
- packages/repl/src/lib/Output/Viewer.svelte
- packages/repl/src/lib/Output/console/ConsoleLine.svelte
- packages/site-kit/src/lib/components/HoverMenu.svelte
- packages/site-kit/src/lib/components/ScreenToggle.svelte
- packages/site-kit/src/lib/components/Text.svelte
- packages/site-kit/src/lib/docs/DocsContents.svelte
- packages/site-kit/src/lib/nav/MobileSubMenu.svelte
- packages/site-kit/src/lib/nav/Nav.svelte
- packages/site-kit/src/lib/nav/SkipLink.svelte
- packages/site-kit/src/lib/search/SearchBox.svelte
- packages/site-kit/src/lib/search/SearchResultList.svelte
- packages/site-kit/src/lib/styles/base.css
if `--sk-fg-2` is the default, we don't need to specify it in a bunch of places. this also fixes a few other things on a drive-by basis
> fix some more css

- packages/repl/src/lib/workers/bundler/index.ts
Older Svelte versions did extend their compiler error from Error without marking the message property as enumerable. Therefore we need to explicitly add it to the destructuring.
> fix: show compiler message for older Svelte versions

- apps/svelte.dev/scripts/sync-docs/index.ts
Not everyone might be interested in having all repos locally linked up, and only care about locally syncing/updating specific repos at a time. That's currently not possible because the sync script error with a somewhat hard to understand error, because it can't find a certain repo. This adds a dedicated check and shows a warning instead of erroring.
> chore: warn instead of error when no linked repo found

- apps/svelte.dev/src/routes/docs/[...path]/OnThisPage.svelte
- packages/repl/src/lib/Input/ComponentSelector.svelte
- packages/repl/src/lib/Output/CompilerOptions.svelte
- packages/site-kit/src/lib/nav/MobileMenu.svelte
- packages/site-kit/src/lib/nav/Nav.svelte
- packages/site-kit/src/lib/search/Search.svelte
- packages/site-kit/src/lib/styles/tokens/colours.css
deletes some redundant styles, makes a couple of tiny things more consistent
> More css tweaks

- packages/editor/src/lib/Workspace.svelte.ts
- packages/editor/src/lib/codemirror.css
- packages/repl/src/lib/Input/ComponentSelector.svelte
closes #763 and generally simplifies/robustifies things
> Fix file panel

- packages/site-kit/src/lib/markdown/renderer.ts
- packages/site-kit/src/lib/markdown/utils.ts
> fix smart quotes

- apps/svelte.dev/src/lib/icons/chevron.svg
- apps/svelte.dev/src/routes/docs/[...path]/OnThisPage.svelte
- packages/editor/src/lib/Editor.svelte
- packages/editor/src/lib/codemirror.css
- packages/site-kit/src/lib/components/Text.svelte
- packages/site-kit/src/lib/search/SearchResultList.svelte
> nicer gutters

- .github/workflows/docs-preview-create.yml
- apps/svelte.dev/scripts/sync-docs/index.ts
- apps/svelte.dev/scripts/sync-docs/utils.ts
step one of #59 — create a new workflow that runs on a `docs-preview-create` repository dispatch. The idea is that every push to a PR on `svelte` or `kit` or `cli` will cause a preview branch to be created.
TODO
> create docs-preview-create workflow

- .github/workflows/docs-preview-create.yml
> create comments on PRs with deployment preview links

- packages/editor/src/lib/compile-worker/worker.ts
- pass dom/ssr instead of client/server for `generate`
- don't pass `modernAst`, will crash the whole view with an "unknown option" error
> fix: ensure correct options for Svelte 3/4

- apps/svelte.dev/scripts/sync-docs/README.md
this allows PRs from external contributors to trigger previews
> use pull_request_target instead of pull_request

- apps/svelte.dev/scripts/sync-docs/README.md
> docs: add docs for windows symbolic links for `sync-docs` command

- apps/svelte.dev/scripts/sync-docs/index.ts
Running `pnpm sync-docs -w` resulted in the message `watching for changes in` being printed, without displaying the names of the packages it was actually watching
> chore: print correct packages in `watching for changes` message

- .github/workflows/sync-docs.yml
the workflow to create `sync/svelte` preview branches is failing because of some bullshit. this should fix it
> change sync branch names

- apps/svelte.dev/content/tutorial/02-advanced-svelte/02-snippets/01-snippets-and-render-tags/index.md
Replace hard coded text "see no evil" with `{description}` in `monkey` snippet so that it is inline with the solution.
Did not feel like a big enough change that needed an issue, however I can create one if required 🙂
> docs(snippets-and-render-tags): Replace hard coded text

- apps/svelte.dev/content/tutorial/02-advanced-svelte/01-advanced-reactivity/01-raw-state/index.md
Fixed a Typo in 01-advanced-reactivity 01-raw-state.
I am not sure if this belongs in this repo or in sveltejs/svelte, but I couldn't find the advanced tutorial in there.
> docs: Fix Typo in advanced tutorial

- apps/svelte.dev/content/examples/17-special-elements/04-svelte-document/+assets/App.svelte
Svelte Repl isn't working without `.toString()` on the selection.
> fix: repl example '<svelte:document>'

- apps/svelte.dev/content/tutorial/01-svelte/03-props/03-spread-props/index.md
- packages/site-kit/src/lib/codemirror/autocompletionDataProvider.js
The playground suggested using the $state.frozen rune, which was removed, but not $state.raw, its replacement.
This PR fixes that.
> fix: update all $state.frozen autocomplete sugestions to $state.raw

- apps/svelte.dev/src/routes/tutorial/[...slug]/Controls.svelte
The `actual_slug` computation in `Controls.svelte` was incorrectly handling the slug format, which led to incorrect values being set in the `<select>` element.
- Modified the logic in line 20 to correctly determine the `actual_slug` based on whether "kit" is present in `parts[1]`.
- Updated the computation to use `parts[1].includes('kit') ? 'kit' : 'svelte'` to ensure the correct slug format.
> fix: incorrect value in <select> element.

- apps/svelte.dev/content/docs/kit/98-reference/10-@sveltejs-kit.md
- apps/svelte.dev/content/docs/svelte/98-reference/20-svelte.md
- apps/svelte.dev/content/docs/svelte/98-reference/21-svelte-reactivity.md
- apps/svelte.dev/scripts/sync-docs/types.ts
we auto-generate these blocks for each module...
...but we only include function and variable declarations, not classes, meaning that stuff gets excluded from e.g. `svelte/reactivity`
> include classes in exports

- apps/svelte.dev/content/docs/svelte/02-runes/02-$state.md
- apps/svelte.dev/content/tutorial/04-advanced-sveltekit/05-advanced-loading/01-universal-load-functions/index.md
This PR updates the sample code in the SvelteKit tutorial for universal load functions. Specifically, the `<svelte:component>` tag, which is deprecated in `runes` mode, is replaced with a recommended alternative.
Using `<svelte:component>` in the tutorial causes the following warning:
```
svelte:component is deprecated in runes mode — components are dynamic by default (svelte_component_deprecated)
```
The editor's solution already uses the updated code, but the sample code in the tutorial did not reflect this change.
> docs: update sample code to replace deprecated <svelte:component>

- apps/svelte.dev/src/hooks.client.js
- apps/svelte.dev/src/routes/(authed)/playground/[id]/+page.svelte
- packages/editor/src/lib/compile-worker/worker.ts
- packages/repl/src/lib/workers/bundler/index.ts
- packages/site-kit/package.json
- packages/site-kit/src/lib/polyfills/index.ts
- packages/site-kit/src/lib/search/search.ts
- polyfills for `at` and `withResolvers`
- avoid using `structuredClone`, we can use `JSON.parse(JSON.stringify(..))` instead at that position
makes the site work in more browsers
closes #911 assuming we're fine with not supporting Safari 13 and lower (or similarly old browsers; i.e. earlier than ~2020)
> fix: add polyfills / avoid using `structuredClone`

- apps/svelte.dev/content/blog/2024-12-01-advent-of-svelte.md
waiting on a bugfix before we ship this
> advent of svelte day 4

- apps/svelte.dev/src/routes/blog/rss.xml/+server.js
Renders the full post in the RSS feed for the svelte blog. With this change the feed will be friendlier for those with unstable connections (e.g. subway) since you can download posts whenever you have a connection rather than having to navigate to an external URL each time. It's a nicer experience since you don't have to move away from your reader.
Closes https://github.com/sveltejs/svelte.dev/issues/837.
Tested on NetNewswire from localhost feed and it works well.
If this is a documentation PR (i.e. changing content within `apps/svelte.dev/content/docs`), then this is the wrong repository to make those changes. The content in this folder is synced from other repositories. Therefore, these changes should be made in their respective repositories (at https://github.com/sveltejs/svelte or …
> feat: Render full posts on RSS feed

- apps/svelte.dev/scripts/sync-docs/types.ts
means that links are correct in preview deployments
> strip origin from links in deprecation notices

- apps/svelte.dev/content/docs/svelte/03-template-syntax/03-each.md
The documentation has the definition of types supported by #each in svelte 3 right after the version of svelte 4, which started supporting iterables
> fix: Remove duplicate info about {#each} block

- apps/svelte.dev/src/lib/components/ModalDropdown.svelte
- apps/svelte.dev/src/lib/components/SelectIcon.svelte
- apps/svelte.dev/src/routes/(authed)/playground/[id]/AppControls.svelte
- apps/svelte.dev/src/routes/tutorial/[...slug]/Controls.svelte
- packages/site-kit/src/lib/actions/focus.ts
- packages/site-kit/src/lib/styles/index.css
- packages/site-kit/src/lib/styles/utils/nav.css
> better nav

- apps/svelte.dev/src/lib/components/ModalDropdown.svelte
- packages/site-kit/src/lib/components/Text.svelte
- packages/site-kit/src/lib/search/SearchResultList.svelte
- packages/site-kit/src/lib/styles/utils/nav.css
For Chromium-based browsers and Firefox, setting `display: block` or `display: flex` on a `<summary>` element will hide the expand/contract arrow icon. Svelte does this and provides alternative affordances to indicate whether the summary is open.
Safari needs a bit more help, requiring `display:none` on the `::-webkit-details-marker` pseudoelement.
This PR adds `::-webkit-details-marker` to the 4 places I could find summary elements, making Safari consistent with other browsers.
Before:
After:
Before:
After:
Before:
After:
e.g. on https://svelte.dev/blog/view-transitions
Before:
After:
> fix: make Safari rendering of summary elements the same as other browsers

- packages/editor/package.json
- packages/repl/package.json
- packages/site-kit/package.json
- pnpm-lock.yaml
To fix #925 issue, I reported this bug to codemirror and they fixed it. (https://github.com/codemirror/dev/issues/1487)
So I updated package version of `codemirror/view` and we can see white caret in dark mode on mobile safari.
Changed the version of codemirror in below packages.
- /packages/editor
- /packages/repl
- /packages/site-kit
Circled in red
> fix: Update package version of codemirror/view to fix carret low contrast

- apps/svelte.dev/src/lib/server/content.ts
- apps/svelte.dev/src/routes/e/[code]/+page.server.ts
- apps/svelte.dev/src/routes/e/codes.json/+server.ts
- apps/svelte.dev/src/routes/e/tmp/codes.json/+server.ts
This establishes a new route `e/[code]` which serves as a stable reference for all of our warning/error codes. All links to warnings/errors from the Svelte compiler/runtime should go through this route in order to have stable references. That way we can move codes between warnings/errors/different pages or even adjust codes without breaking links.
Part of https://github.com/sveltejs/svelte/issues/11305
> feat: add stable route for all warning/error codes

- apps/svelte.dev/src/lib/server/content.ts
Should address the broken tutorials around `.env` handling: https://github.com/sveltejs/svelte.dev/issues/690
I added just the `.env` files to the glob import, not sure if it makes to include all dot-prefixed files, and from what I understand, Vite's glob import doesn't support the `dot: true` option in `tinyglobby`
> fix: include .env files in tutorial assets

- packages/repl/src/lib/workers/bundler/index.ts
This allows us to do things like this in the playground:
```js
import foo from 'foo@next';
```
My main motivation is so that I can import `@threlte/core@next`, though it doesn't currently work for unrelated reasons
> support importing different versions of packages

- packages/repl/src/lib/workers/bundler/index.ts
- packages/repl/src/lib/workers/bundler/semver.ts
At present, we always import the `latest` version of whatever gets imported. If the dependency is transitive, this often results in the wrong version being imported.
With this PR, we determine the correct version by inspecting the importer's package.json.
> import correct version, as determined by package.json

- apps/svelte.dev/src/routes/_home/Testimonials.svelte
Hi! This PR is a fix of responsive issue in svelte.dev homepage: https://github.com/sveltejs/svelte.dev/issues/982. I see the update version of `@sveltejs/enhanced-img` in commit https://github.com/sveltejs/svelte.dev/commit/d6a64f82bef4e1fc6226390698d63722613e746c makes the svelte.dev homepage not responsive. If I see more detail, the `svelte-pronounciation.svg` needs to set width and height expicitly as the quick solution. 
I have see the PR of `@sveltejs/enhanced-img` https://github.com/sveltejs/kit/pull/13126/files#diff-f318d5cf67f7e975aecc26dfb6056ae55058442cf36dd7e6f53c4a292edeb2d9. But, it looks like Ben forgot to test the `svelte-pronounciation.svg` asset.
Here's the GIF video demonstration (please wait for seconds to make it appears).
> Fix Responsive Issue in svelte.dev Homepage

- apps/svelte.dev/content/examples/09-transitions/06-deferred-transitions/+assets/App.svelte
The deferred-transitions example was doing "===" comparison with a proxy, this pr fixes that by using $state.raw instead of $state
> fix: state_proxy_equality_mismatch error in deferred-transitions example

- packages/site-kit/src/lib/markdown/renderer.ts
fixes #647 
the typeExpression of a JSDocTypeTag is truncated due to comment syntax.
| AS-IS | TO-BE |
|--------|--------|
| <img width="980" alt="image" src="https://github.com/user-attachments/assets/3bdd1fd2-7835-47e7-8cdf-47e5e085e52e" /> | <img width="789" alt="image" src="https://github.com/user-attachments/assets/d176e8b2-5fd0-4ba8-90fa-7eac45bc7fdb" /> |  
This PR addresses an issue where the typeExpression of a JSDocTypeTag was being truncated due to comment syntax (e.g., // ...) when converting JavaScript code with JSDoc to TypeScript.
It appears there is a bug in TypeScript’s parsing of the JSDoc `@type` tag, where it assigns the typeExpression property incorrectly ([parseJSDocTypeExpression](https://github.com/microsoft/TypeScript/blob/f69580f82146bebfb2bee8c7b8666af0e04c7e34/s …
> fix: replace incorrect jsdoc typeExpression in AST traversal

- apps/svelte.dev/package.json
- packages/editor/package.json
- packages/editor/src/lib/Editor.svelte
- packages/repl/package.json
- packages/site-kit/package.json
- packages/site-kit/src/lib/nav/MobileMenu.svelte
- packages/site-kit/src/lib/nav/Nav.svelte
- packages/site-kit/src/lib/search/SearchBox.svelte
- pnpm-lock.yaml
need to avoid parens being added around function bindings
> bump prettier-plugin-svelte

- apps/svelte.dev/.env
- apps/svelte.dev/README.md
- apps/svelte.dev/src/routes/(authed)/+layout.server.js
- apps/svelte.dev/src/routes/+layout.server.ts
- apps/svelte.dev/src/routes/+page.server.js
- apps/svelte.dev/src/routes/blog/+page.server.js
- apps/svelte.dev/src/routes/blog/[slug]/+page.server.js
- apps/svelte.dev/src/routes/chat/+server.js
- apps/svelte.dev/src/routes/docs/+page.server.js
- apps/svelte.dev/src/routes/docs/[...path]/+layout.server.ts
- apps/svelte.dev/src/routes/docs/kit/modules/+page.svelte
- apps/svelte.dev/src/routes/e/[code]/+page.server.ts
- apps/svelte.dev/src/routes/tutorial/[...slug]/+page.server.ts
This PR tweaks prerender config. By default, everything is prerendered except `/e/[slug]`, `/apps`, and `/playground/[slug]`, but if `PRERENDER=false` then it will be disabled for everything except a few server routes.
This means you can do `PRERENDER=false pnpm build` and everything builds _waaaaay_ faster, which is useful for debugging production issues locally.
> make prerender configurable

- apps/svelte.dev/content/blog/2024-12-01-whats-new-in-svelte-december-2024.md
- apps/svelte.dev/content/docs/kit/10-getting-started/10-introduction.md
- apps/svelte.dev/content/docs/kit/20-core-concepts/50-state-management.md
- apps/svelte.dev/content/docs/kit/60-appendix/50-additional-resources.md
- apps/svelte.dev/content/docs/kit/98-reference/10-@sveltejs-kit.md
- apps/svelte.dev/content/docs/kit/98-reference/50-configuration.md
- apps/svelte.dev/content/docs/svelte/98-reference/20-svelte.md
- apps/svelte.dev/content/tutorial/01-svelte/01-introduction/01-welcome-to-svelte/index.md
- apps/svelte.dev/content/tutorial/04-advanced-sveltekit/07-conclusion/01-next-steps/index.md
per https://github.com/sveltejs/svelte.dev/pull/1059/files#r1895886485, we have fully qualified links that should be root-relative (so that they work in preview deployments and locally). this updates the ones on `main`
> docs: use root-relative links instead of https://svelte.dev

- apps/svelte.dev/src/routes/docs/+page.svelte
https://svelte.dev/docs is missing `<title>`
> chore: add title to root docs page

- apps/svelte.dev/content/tutorial/04-advanced-sveltekit/04-advanced-routing/04-route-groups/index.md
Fixes code block so that it is aligned with the [solved file](https://github.com/sveltejs/svelte.dev/blob/main/apps/svelte.dev/content/tutorial/04-advanced-sveltekit/04-advanced-routing/04-route-groups/%2Bassets/app-b/src/routes/(authed)/%2Blayout.svelte#L5).
> fix: Add missing {@render children()} in tutorial

- apps/svelte.dev/content/tutorial/01-svelte/04-logic/05-keyed-each-blocks/index.md
I know it's a very small change, but the missing "rather" annoys me.
> fix: Improve the readability of 05-keyed-each-blocks in tutorial

- packages/site-kit/package.json
- packages/site-kit/src/lib/actions/legacy-details.ts
- packages/site-kit/src/lib/components/Banner.svelte
- packages/site-kit/src/lib/components/Text.svelte
- packages/site-kit/src/lib/nav/Nav.svelte
- packages/site-kit/src/lib/search/Search.svelte
- packages/site-kit/src/lib/search/SearchBox.svelte
- packages/site-kit/src/lib/state/code_preference.ts
- packages/site-kit/src/lib/state/search.svelte.ts
- packages/site-kit/src/lib/stores/index.ts
- packages/site-kit/src/lib/stores/prefers_ts.ts
- packages/site-kit/src/lib/stores/search.ts
- pnpm-lock.yaml
quick follow-up to #1087 — removes a dependency (and various store uses) in favour of the `Persisted` class
> remove svelte-persisted-store

- apps/svelte.dev/content/tutorial/03-sveltekit/07-api-routes/03-other-handlers/+assets/app-b/src/routes/+page.svelte
- apps/svelte.dev/content/tutorial/03-sveltekit/07-api-routes/03-other-handlers/index.md
[Other handlers tutorial](https://svelte.dev/tutorial/kit/other-handlers) is broken, because data prop is not _deeply_ reactive.
See issues #1079 and #1069 for more details.
> Fix: SvelteKit other-handlers tutorial

- apps/svelte.dev/src/hooks.server.js
- apps/svelte.dev/src/routes/repl/[...path]/+page.server.ts
> fix: repl redirect to playground

- apps/svelte.dev/scripts/sync-docs/types.ts
For reasons I don't understand, classes with private fields get an uninitialized `#private` property added to the emitted declaration file, causing this:
It's bizarre and useless, so we just remove it
(aside: `SvelteMap` and its siblings need some inline docs. ideally we'd be able to hide unnecessary properties and methods with `@internal` but that doesn't seem to work)
> docs: remove useless private fields

- apps/svelte.dev/content/tutorial/01-svelte/09-transitions/04-custom-css-transitions/+assets/app-a/src/lib/App.svelte
- apps/svelte.dev/content/tutorial/01-svelte/09-transitions/04-custom-css-transitions/+assets/app-b/src/lib/App.svelte
- apps/svelte.dev/content/tutorial/01-svelte/09-transitions/04-custom-css-transitions/index.md
Currently [this page](https://svelte.dev/tutorial/svelte/custom-css-transitions) of tutorial speaks how function receives two arguments, `t` and `u` where `u = 1 - t` but them proceeds to use `1-t`.
This is not much but an honest fix.
> fix: using `u` as in the description

- apps/svelte.dev/content/tutorial/02-advanced-svelte/05-advanced-transitions/01-deferred-transitions/+assets/app-a/src/lib/App.svelte
- apps/svelte.dev/content/tutorial/02-advanced-svelte/05-advanced-transitions/01-deferred-transitions/+assets/app-a/src/lib/TodoList.svelte
- apps/svelte.dev/content/tutorial/02-advanced-svelte/05-advanced-transitions/01-deferred-transitions/+assets/app-b/src/lib/TodoList.svelte
- apps/svelte.dev/content/tutorial/02-advanced-svelte/05-advanced-transitions/02-animations/+assets/app-b/src/lib/TodoList.svelte
The tutorial on advanced animations (see [this](https://svelte.dev/tutorial/svelte/deferred-transitions) and [this](https://svelte.dev/tutorial/svelte/animations)) is using `todo.id` without ever defining `id`.
For example, in TodoList.svelte, it says:
```svelte
<li
class={{ done: todo.done }}
in:receive={{ key: todo.id }}
out:send={{ key: todo.id }}
>
```
However, the todos are defined in App.svelte like this:
```svelte
const todos = $state([
{ done: false, description: 'write some docs' },
{ done: false, description: 'start writing blog post' },
{ done: true, description: 'buy some milk' },
{ done: false, description: 'mow the lawn' },
{ done: false, description: 'feed the turtle' },
{ done: false, description: 'fix some bugs' }
]);
```
This PR adds the `id` to the todos, and also uses …
> docs: Fixed TODO id in animation tutorial

- .github/workflows/docs-preview-create.yml
- .github/workflows/docs-preview-delete.yml
- .github/workflows/sync-docs.yml
He doesn't deserve the power
This switches the workflows to `workflow_dispatch` triggers, which will also let us manually start them from the Actions interface if we ever need to.
> feat: Remove Rich Harris as commenter on preview comments

- .github/workflows/docs-preview-create.yml
I'm adding requests to create docs on pushes (so that PRs stay up to date if they add changes to docs later). This just makes sure that if someone pushes to the same PR a bunch of times, we don't run a bunch of concurrent jobs.
> feat: Add concurrency to docs-preview-create.yml

- packages/editor/src/lib/compile-worker/worker.ts
- packages/repl/src/lib/workers/bundler/index.ts
this was already possible before — the regex is pretty dumb, so `pr-<branch>` and `commit-<branch>` also work — but this PR formalises it
> allow branch playground urls

- apps/svelte.dev/src/routes/docs/+page.svelte
People are having trouble finding the v3/v4 docs. Hopefully this helps some
> docs: link to old site in welcoming directory

- apps/svelte.dev/content/blog/2025-02-01-whats-new-in-svelte-february-2025.md
lemme know if i missed anything
> docs: "What's new in Svelte" February newsletter

- apps/svelte.dev/content/tutorial/03-sveltekit/09-errors-and-redirects/04-redirects/index.md
This is remaining work from [the tutorial update from SvelteKit 1 to 2](https://github.com/sveltejs/svelte.dev/commit/1fc5055f0f0aca9cc4611900c7d2494512cb088e#diff-bf2d1cf2d0668155a5de372c1a78a12e766e3a6f51ac7aa552c2771c24564c27). This fixes a remaining mention of `throw`ing `redirect`s on the [redirects tutorial step](https://svelte.dev/tutorial/kit/redirects).
> We can also use the throw mechanism to redirect from one page to another.
This PR is for the tutorial, which is maintained in this svelte.dev repo, not the docs in the sveltekit repo.
> docs: Fixed old reference to throwing redirects in SvelteKit tutorial

- .github/workflows/docs-preview-create.yml
I recently locked down default permissions in the `sveltejs` org, and as a result workflows are failing in this repo. This _might_ help
> chore: update permissions

- packages/site-kit/src/lib/markdown/renderer.ts
This converts `/** @type {Foo} */ (foo)` to `foo as Foo`, which is necessary for a PR I plan to make on `sveltejs/svelte` shortly
> fix: convert type assertions

- apps/svelte.dev/src/routes/(authed)/playground/[id]/embed/+page.svelte
- packages/repl/src/lib/Output/Output.svelte
- packages/repl/src/lib/Repl.svelte
Embed mode, but with hash support and a new query param that makes it so only the output is shown, nothing else
> chore: output-only embedded mode

- apps/svelte.dev/src/routes/blog/rss.xml/+server.js
small QOL fix — this allows `/blog/rss.xml` to open inline in the browser instead of triggering a download. For whatever reason `application/rss+xml`, while 'correct', yields unhelpful results.
The cache control header doesn't do anything since this route is prerendered, so I got rid of it.
> fix rss.xml headers

- packages/site-kit/package.json
- pnpm-lock.yaml
Bumping these as part of an attempt to figure out why `/blog/rss.xml` keeps failing to build on Vercel (apparently we're indirectly using `createShikiInternalSync` somewhere rather than `createShikiInternal`, and it needs to have the languages loaded upfront? except that sometimes it works and I have no idea how to reliably reproduce it)
> bump shiki and twoslash

- apps/svelte.dev/src/routes/_home/Footer.svelte
Automates the year in the footer using `new Date().getFullYear()`
Resolves #1171
> fix: Automate year in footer

- apps/svelte.dev/src/routes/_home/Footer.svelte
- apps/svelte.dev/src/routes/docs/[...path]/+page.svelte
alternative to #1165 that breaks after slashes, rather than in the middle of words. This is a scenario-solve, but it works well
> insert `<wbr>` elements to break package names

- apps/svelte.dev/src/lib/components/ModalDropdown.svelte
- apps/svelte.dev/src/routes/(authed)/apps/+page.svelte
- apps/svelte.dev/src/routes/(authed)/playground/[id]/AppControls.svelte
- apps/svelte.dev/src/routes/_home/Community.svelte
- apps/svelte.dev/src/routes/_home/Companies.svelte
- apps/svelte.dev/src/routes/_home/Supporters/index.svelte
- apps/svelte.dev/src/routes/_home/Testimonials.svelte
- apps/svelte.dev/src/routes/docs/+page.svelte
- apps/svelte.dev/src/routes/tutorial/[...slug]/+page.svelte
- packages/site-kit/src/lib/components/Dropdown.svelte
got tired of looking at a bunch of warnings every time i ran `pnpm check`, this fixes them
> squelch warnings

- apps/svelte.dev/content/blog/2025-04-01-whats-new-in-svelte-april-2025.md
Feel free to add a comment if I missed anything!
> docs: "What's new in Svelte" April newsletter

- apps/svelte.dev/src/routes/docs/[...path]/OnThisPage.svelte
Fixes [#1183](https://github.com/sveltejs/svelte.dev/issues/1183)
On certain screen resolutions and specific pages, the "On This Page" navigation text appears to overflow or sit too close to the container edge. 
- Added a right padding of `1rem` to the "On This Page" navigation container.
- This ensures proper spacing and improves readability, preventing text from appearing too close to or overflowing the container edge.
| Before                                                                                       | After                                                                                        |
| -------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- …
> fix: adjust right padding in OnThisPage component to fix text overflow

- apps/svelte.dev/content/tutorial/01-svelte/05-events/04-component-events/+assets/app-a/src/lib/Stepper.svelte
- apps/svelte.dev/content/tutorial/01-svelte/05-events/04-component-events/index.md
|How it was|How it is now|
|-|-|
|<img width="439" alt="Снимок экрана 2025-02-04 в 11 49 53" src="https://github.com/user-attachments/assets/76d8da64-21bd-471c-8570-a5475d0fcea8" />|<img width="450" alt="Снимок экрана 2025-02-04 в 11 50 00" src="https://github.com/user-attachments/assets/4315e30e-2d1c-4158-b75c-def2f5acd484" />|
The markdown renderer doesn't highlight full diff if it starts in the middle of another span (diff highlighting conflicts with language highlighting). So, ", decrement" is not highlighted because of this bug, it looks a little annoying to me.
Without working on renderer itself we can make it look better and just go around the bug
> fix: diff highlighting for specific example in tutorial

- apps/svelte.dev/src/hooks.server.js
- apps/svelte.dev/src/routes/examples/[...path]/+page.server.ts
---
fixes #1129 .
The following need to be checked on the preview site:
- `/examples` redirects to `/playground`
- `/examples/hello-world` redirects to `/playground/hello-world`
- `/examples/thumbnails/actions.jpg` is not redirected
> fix: correct redirection for examples/[...path]

- packages/repl/src/lib/Output/srcdoc/index.html
The SvelteKit/WebContainer portion of the tutorial has focus management that prevents the iframe from stealing editor focus. When we switched the Svelte tutorial over to Rollup, we forgot to apply it, resulting in things like #700. This should fix it
> prevent iframe from stealing focus from editor

- apps/svelte.dev/content/tutorial/01-svelte/08-actions/01-actions/+assets/app-a/src/lib/Canvas.svelte
> simplify Canvas.svelte in actions tutorial

- packages/repl/src/lib/workers/npm.ts
this allows the use of packages that specify a `"browser"` map of shims
> respect browser overrides

- apps/svelte.dev/src/lib/db/client.js
- apps/svelte.dev/src/routes/tutorial/[...slug]/ImageViewer.svelte
- apps/svelte.dev/src/routes/tutorial/[...slug]/image-viewer-background.svg
- packages/site-kit/src/lib/markdown/renderer.ts
- packages/site-kit/src/lib/markdown/utils.ts
fixes a few build-time warnings, and also fixes the `ImageViewer.svelte` background that's seen (or currently not seen, because it's broken) when you select an image file in e.g. https://svelte.dev/tutorial/svelte/svelte-body
> squelch some warnings

- apps/svelte.dev/package.json
- apps/svelte.dev/vite.config.ts
- packages/site-kit/package.json
- packages/site-kit/src/lib/markdown/renderer.ts
- pnpm-lock.yaml
Am trying to diagnose some annoying build flakiness — it's something to do with shiki failing to load language modules. As a first step this removes version 1, since we use version 3 elsewhere (and the package that imports version 1 doesn't appear to use it?).
There's also some trickery around `ssr.external` that I don't understand
> remove shiki@1

- apps/svelte.dev/src/lib/tutorial/adapters/rollup/index.svelte.ts
- packages/repl/src/lib/Bundler.svelte.ts
- packages/repl/src/lib/workers/bundler/index.ts
- packages/repl/src/lib/workers/workers.d.ts
alternative to #1272 — rather than cluttering files with `<svelte:options>`, I think it's reasonable to opt into runes mode for the duration of the tutorial. It does mean that the 'before' code in a case like https://svelte.dev/tutorial/svelte/universal-reactivity would behave differently if pasted into a project locally, but it serves the same pedagogical goal, and anticipates a future time in which everything is runes mode.
> default to runes mode in tutorial

- apps/svelte.dev/content/tutorial/01-svelte/04-logic/05-keyed-each-blocks/index.md
I personally was confused with the previous explanation as to what it meant that the other list items were updated. Explaining it that egg replaced the name attribute for the doughnut, and doughnut replaced the name attribute for the car node, helped me understand what Svelte was actually doing. Explicitly drawing out what Svelte is doing made it make more sense, but I'm open to feedback! If this doesn't fit the style or is too verbose, I'll try to figure out something else! 
If this is a documentation PR (i.e. changing content within `apps/svelte.dev/content/docs`), then this is the wrong repository to make those changes. The content in this folder is synced from other repositories. Therefore, these changes should be made in their respective repositories (at …
> docs: Improve explanation of 05-keyed-each-blocks in tutorial

- apps/svelte.dev/src/lib/db/client.js
follow-up to #1268 — we still need to check for the presence of these env vars, we just need to make sure we don't try and read dynamic env vars during prerendering or it blows up, hence the `!building` gate
> only create supabase client when env vars are present

- apps/svelte.dev/src/lib/server/content.ts
- apps/svelte.dev/src/routes/docs/[...path]/+layout.server.ts
- packages/site-kit/src/lib/docs/DocsContents.svelte
- packages/site-kit/src/lib/types.d.ts
another case where https://github.com/sveltejs/kit/issues/12458 would be useful — we're accidentally shipping unused data (basically the docs in their entirety) to power the sidebar
> summarize docs

- apps/svelte.dev/src/routes/tutorial/[...slug]/OutputRollup.svelte
- packages/repl/package.json
- packages/repl/src/lib/Output/Viewer.svelte
- packages/repl/src/lib/Output/console/Console.svelte
- packages/repl/src/lib/Output/console/ConsoleLine.svelte
- packages/repl/src/lib/Output/console/Log.svelte.ts
- packages/repl/src/lib/Output/console/index.ts
I ballsed up the migration of `Viewer.svelte` to runes mode, the result being that things are logged incorrectly:
This PR updates the logger to use classes, which are more idiomatic and more performant
> use class-based reacgtivity for logs in playground

- packages/repl/src/lib/Output/Viewer.svelte
Unmount component only if it was successfully mounted to prevent annoying lifecycle_double_unmount warning. Plus always restore console methods.
> fix: prevent lifecycle_double_unmount warning in REPL

- apps/svelte.dev/src/routes/_home/Video.svelte
- packages/repl/src/lib/Output/CompilerOptions.svelte
- packages/site-kit/src/lib/components/Checkbox.svelte
- packages/site-kit/src/lib/docs/DocsContents.svelte
- packages/site-kit/src/lib/markdown/renderer.ts
- packages/site-kit/src/lib/nav/Nav.svelte
i broke the focus rings on the top nav with the `mask-image` stuff — this reinstates it, and improves focus rings in a few other cases
> a11y tweaks

- packages/site-kit/src/lib/codemirror/autocompletionDataProvider.js
follow-up to #1307, which doesn't quite work — it doesn't correctly recognise when you're adding `.id` to an existing `$props()` call. We also don't need a dedicated `is_props_id` function, because if `is_props` worked (which it doesn't currently, but does in this PR) then it's the same test.
> fix `$props()` and `$props.id()` autocompletion

- packages/repl/src/lib/workers/bundler/index.ts
- packages/repl/src/lib/workers/npm.ts
this allows the playground to resolve [subpath imports](https://nodejs.org/api/packages.html#subpath-imports), which is a good thing in general but particularly important if we do https://github.com/sveltejs/svelte/pull/15785
> feat: support pkg.imports in playground

- packages/repl/src/lib/workers/bundler/index.ts
right now you can't do `version=4` in the playground because we're setting the `runes` option indiscriminately
> fix: only set options.runes in svelte >= 5

- packages/repl/src/lib/workers/bundler/index.ts
- packages/repl/src/lib/workers/npm.ts
Without this if you try to launch the playground with `version=local` it will fail to resolve the `pkg.imports` for the local version of svelte.
> fix: resolve imports for `local` version

- apps/svelte.dev/src/routes/+layout.server.ts
we probably should have added this a while back, but better late than never for letting non-social-media/reddit users know that the conference is happening
> Add Barcelona banner

- apps/svelte.dev/src/routes/docs/[topic]/[...path]/llms-small.txt/+server.ts
- apps/svelte.dev/src/routes/docs/llms/+page.svelte
- apps/svelte.dev/src/routes/llms-medium.txt/+server.ts
- apps/svelte.dev/src/routes/llms-small.txt/+server.ts
- apps/svelte.dev/src/routes/llms-small.txt/content-svelte.md
- apps/svelte.dev/src/routes/llms-small.txt/content-sveltekit.md
- apps/svelte.dev/src/routes/llms.txt/template.md
Partially automatically summarized with manual tweaks.
Needs testing before getting merged.
Closes https://github.com/sveltejs/svelte/issues/15677
> chore: provide smaller llms-small.txt

- apps/svelte.dev/src/lib/components/PageControls.svelte
- apps/svelte.dev/src/lib/server/llms.ts
- apps/svelte.dev/src/routes/docs/[topic]/[...path]/+page.svelte
- apps/svelte.dev/src/routes/docs/[topic]/[...path]/llms.txt/+server.ts
- apps/svelte.dev/src/routes/llms-full.txt/+server.ts
- apps/svelte.dev/src/routes/llms-medium.txt/+server.ts
- apps/svelte.dev/src/routes/llms.txt/+server.ts
That way LLMs have it easier getting a clean version of the docs
> chore: add `/llms.txt` containg raw markdown for each docs page

- apps/svelte.dev/src/routes/_home/Testimonials.svelte
Update Testimonials.svelte to link to recent stateofjs report from 2024 instead of 2023
> Update Testimonials.svelte to link to recent stateofjs report

- .github/workflows/docs-preview-create.yml
For long running branches like https://github.com/sveltejs/svelte/pull/15000, the preview can get quite out of date. This PR changes the behaviour such that we always reinitialize the preview branch from `main` before syncing the latest docs
> reinit preview branches from main

- packages/site-kit/src/lib/markdown/renderer.ts
When removing a JSDoc comment in its entirety, we want to keep a preceding newline if the node is multiline, otherwise it looks crunched
> preserve newlines before jsdoc comments where appropriate

- apps/svelte.dev/content/tutorial/01-svelte/04-logic/06-await-blocks/+assets/app-a/src/lib/utils.js
This is almost a non-issue, but the old implementation of a D6 die roll was able to produce zero, although with very low likelihood.
From [the Math.random documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random), my boldface:
> The `Math.random()` static method returns a floating-point, pseudo-random number that's greater than or **equal to 0** and less than 1
It might seem petty and like a waste of time, but I think there's also no reason to keep an error in a tutorial.
Again, there's no issue, but if you feel that it would be valuable I'd be happy to create one.
> fix: D6 die roll could produce 0

- packages/site-kit/src/lib/components/Text.svelte
Addresses an issue where the lightbulb icon pseudo-element was inadvertently capturing pointer events. for underlying elements by being oversized.
- Sets `pointer-events: none` on the icon pseudo-element to prevent unintended interactions.
The size could probably be fixed as well, but this prevents any unintentional pointer events since this appears to be only artistic anyway.
<small>Seen on https://svelte.dev/docs/svelte/use</small>
> fix: Prevents lightbulb pseudo element from blocking interactivity with underlying contents

- packages/site-kit/src/lib/markdown/renderer.ts
this does two things — it ensures that we don't insert double newlines...
...and ensures that we _do_ add a newline if either the current node or the preceding node spans multiple lines. In other words we can convert this
```js
/** @type {Foo[]} */
let foo = [];
/** @type {Bar[]} */
let bar = [];
```
to this
```ts
let foo: Foo[] = [];
let bar: Bar[] = [];
```
but if either the `foo` or `bar` declaration spans multiple lines, we want to have a newline between them after the conversion.
> improve jsdoc conversion

- apps/svelte.dev/content/blog/2025-06-01-whats-new-in-svelte-june-2025.md
Let me know if I missed anything!
> docs: "What's new in Svelte" June newsletter

- packages/repl/package.json
- packages/repl/src/lib/workers/bundler/index.ts
- packages/repl/src/lib/workers/bundler/plugins/typescript.ts
- packages/repl/src/lib/workers/compiler/index.ts
- packages/repl/src/lib/workers/typescript-strip-types.ts
- pnpm-lock.yaml
Instead of using `ts-blank-space` we're using custom logic that closely follows that of https://github.com/sveltejs/svelte/blob/main/packages/svelte/src/compiler/phases/1-parse/remove_typescript_nodes.js . That way we shrink the worker bundle by about 9x.
Tested by pasting https://github.com/sveltejs/svelte/blob/main/packages/svelte/tests/runtime-runes/samples/typescript/main.svelte (minus the script tags/template) into a `.ts` file
> Strip TS types ourselves

- packages/repl/src/routes/+layout.server.ts
- packages/repl/src/routes/+page.svelte
- packages/repl/src/routes/v0.svelte
- packages/repl/svelte.config.js
- packages/repl/vite.config.ts
This is used to bundle a SvelteKit playground app that can then be embedded in v0
Since rarely anyone builds/runs the playground directly (only through the app) this should be fine to land (and you can always comment in the old thing to play around with stuff)
> chore: add v0 build setup

- packages/repl/src/lib/workers/bundler/index.ts
- packages/repl/src/lib/workers/bundler/plugins/commonjs.ts
Handle some edge cases around default exports, a especially weird code snippet of a specific very popular but abandoned library, and bail in more cases for perf
> fix: faster/more robust commonjs playground plugin

- packages/repl/src/lib/Output/Viewer.svelte
- packages/repl/src/lib/public.d.ts
- packages/repl/src/lib/workers/bundler/index.ts
Add support for things like `import './app.css'`, which can also influence tailwind's output
> feat: support CSS imports in playground

- apps/svelte.dev/src/routes/(authed)/playground/[id]/+page.svelte
- packages/repl/src/lib/workers/bundler/index.ts
- packages/repl/src/lib/workers/bundler/plugins/alias.ts
- ensure tailwind tokens are preserved when rebundling with cache
- ensure cache is created the first time already and available for the second run
- more robust resolution
- pass better filename for compiler so __svelte_meta.loc.file is more useful (v0 needs this for analysis)
> fix: make repl more robust

- packages/site-kit/src/lib/components/Text.svelte
fixes #1403
`/packages/site-kit/src/lib/components/Text.svelte`
This issue is due to selecting wrong targeted element.
I changed query for selecting document.
```js
parent.querySelector(`pre[data-language="${ts ? 'ts' : 'js'}"] code`) as HTMLElement;
```
The change improves the logic for selecting code blocks based on the language toggle by explicitly filtering for the `ts` or `js` language instead of relying on positional selectors.
> fix: copy the correct code block

- apps/svelte.dev/content/tutorial/01-svelte/02-reactivity/03-derived-state/index.md
As mentioned in [the docs](https://svelte.dev/docs/svelte/$derived#Overriding-derived-values):  "Prior to Svelte 5.25, deriveds were read-only."
Also the playground seems to use a version >= 5.25. Assigning to a derived value works fine.
> docs: remove old info about assigning derived state

- packages/repl/src/lib/Output/console/ConsoleLine.svelte
This has been bugging me for a while...if you have duplicate logs the counter doesn't actually go up...the reason is that `ConsoleLine` is a svelte 4 component using `Log` which is a svelte 5 class.
Well at least it was before this PR 😄
> fix: migrate `ConsoleLine` to svelte 5 to show the right count for duplicate logs

- .github/PULL_REQUEST_TEMPLATE.md
This PR changes the PR template to make the note on documentation PRs a comment instead of content. Otherwise, it'll be included in every PR description. See below for an example.
> chore: make the note on documentation PRs a comment

- packages/site-kit/src/lib/nav/Nav.svelte
This was discussed in the maintainers channel on Discord.
> fix: change bsky link from svelte society to svelte

- packages/site-kit/src/lib/nav/MobileMenu.svelte
- packages/site-kit/src/lib/nav/Nav.svelte
> fix: change mobile nav to link to svelte.dev bsky

- .github/workflows/docs-preview-create.yml
Need this here to keep track of it so we can sync the Vercel statuses back
> chore: Add check ID to docs create workflow

- apps/svelte.dev/content/docs/kit/20-core-concepts/60-remote-functions.md
- apps/svelte.dev/content/docs/kit/98-reference/10-@sveltejs-kit.md
We shouldn't have published these docs — see https://github.com/sveltejs/kit/pull/14304#discussion_r2299299623. For now I'm just going to revert, will review https://github.com/sveltejs/kit/pull/14304 (which updates them) later
> Revert "Sync `kit` docs"

- apps/svelte.dev/src/routes/(authed)/playground/[id]/gzip.js
For some reason, certain sites (Discord) don't like it when you send links ending in `=`, and `=`s are only for optional padding in base64, so this should fix that.
> fix: remove trailing `=` signs from hash urls

- packages/site-kit/src/lib/search/SearchBox.svelte
Currently, the background of scrollbar in the search results modal is transparent.
It should have the same background color as the modal.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> fix: scrollbar background on search results

- apps/svelte.dev/package.json
- pnpm-lock.yaml
need this before we can merge any further updates to Kit docs, which don't typecheck without the latest version because of `query.batch`
> chore: bump kit

- apps/svelte.dev/src/lib/server/llms.ts
- apps/svelte.dev/src/routes/llms-medium.txt/+server.ts
Fixes #1463 
This PR fixes broken formatting in `llms-medium.txt` file by updating the regex in `llms.ts` file to preserve newlines and tabs for indentation.
> fix(llms): preserve newlines in generated `llms-medium.txt` file

- apps/svelte.dev/content/tutorial/01-svelte/06-bindings/04-select-bindings/+assets/app-a/src/lib/App.svelte
- apps/svelte.dev/content/tutorial/01-svelte/06-bindings/04-select-bindings/+assets/app-b/src/lib/App.svelte
Closes #1527 
This PR removes unnecessary `$state` rune from the static questions array in select-bindings tutorial.
> chore(tutorial/select-bindings): remove unnecessary `$state` rune

- apps/svelte.dev/src/routes/packages/PackageCard.svelte
so that we use client-side nav for e.g. the adapters
> use internal links for first party packages

- packages/site-kit/src/lib/markdown/utils.ts
#1587 introduced a bad regex — we need the `?` to make the pattern non-greedy. Without it, we're missing headings — https://svelte.dev/docs/kit/load currently looks like this...
...when it should look like this:
I also changed the hard-coded three backticks to a minimum of three, so that we can potentially do this sort of thing in future:
`````
````md
this is a code fence:
```js
console.log('woooo!');
```
````
`````
> fix headings
