apps/svelte-omnisite.vercel.app/README.md
just want to see if this creates a preview deployment or if something is broken
=> trying to diagnose deploy failure

apps/svelte.dev/src/routes/tutorial/[...slug]/Sidebar.svelte, packages/site-kit/src/lib/components/Text.svelte
fixes https://github.com/sveltejs/svelte.dev/issues/445
=> chore: hide copy button

apps/svelte.dev/content/tutorial/01-svelte/05-events/02-inline-handlers/index.md
Added $state rune to Tutorial example to reflect actual 'solve' code in editor.
=> chore: Added $state rune to Tutorial example

apps/svelte.dev/content/tutorial/01-svelte/04-logic/04-each-blocks/index.md, apps/svelte.dev/content/tutorial/02-advanced-svelte/08-script-module/02-module-exports/index.md
Pull request to fix the issue #587
Modify on:click to onclick on Svelte 5 examples
=> Fix for issue #587: remove some deprecated on:click

packages/editor/src/lib/Workspace.svelte.ts
alternative to #593 that avoids adding internal implementation details to the `Workspace` public API
=> separate state updates from file updates

apps/svelte.dev/content/tutorial/02-advanced-svelte/07-special-elements/05-svelte-head/index.md
=> fix: make href point to the correct path

apps/svelte.dev/src/routes/tutorial/[...slug]/+page.svelte
=> account for banner when sizing tutorial screen

apps/svelte.dev/src/hooks.server.js, apps/svelte.dev/src/routes/docs/component-directives/+page.svelte, apps/svelte.dev/src/routes/docs/element-directives/+page.svelte, apps/svelte.dev/src/routes/docs/special-elements/+page.svelte
ref https://github.com/sveltejs/svelte.dev/issues/540
Remaining migrations for Svelte 4 docs
=> Svelte docs migration

packages/site-kit/src/lib/docs/DocsContents.svelte
=> account for banner height in docs sidebar

apps/svelte.dev/package.json, apps/svelte.dev/src/routes/+layout.svelte, pnpm-lock.yaml
closes #706. will self-merge so that we can start gathering data to check that it worked
=> add analytics

apps/svelte.dev/src/routes/docs/+page.svelte
=> adjust margin/padding on `/docs`

apps/svelte.dev/svelte.config.js
should save us three or four network requests
=> set inlineStyleThreshold

packages/site-kit/src/lib/search/SearchBox.svelte
=> Change Search Box escape key from e.code to e.key

packages/editor/src/lib/codemirror.css
fixes something I broke in #735. will instamerge because it makes the playground hard to use
=> gah why would you put the active line above the selection

packages/editor/src/lib/close-dark.svg, packages/editor/src/lib/close-light.svg, packages/editor/src/lib/codemirror.css
=> fix codemirror search panel

packages/site-kit/src/lib/nav/MobileSubMenu.svelte
=> fix nav submenu autoscroll

packages/editor/src/lib/Workspace.svelte.ts, packages/editor/src/lib/codemirror.css
closes #431 (though we still need to populate the detail for most of these)
=> link to docs from diagnostics

apps/svelte.dev/src/routes/tutorial/[...slug]/filetree/ContextMenu.svelte, apps/svelte.dev/src/routes/tutorial/[...slug]/filetree/Item.svelte
=> make context menu work properly

.github/workflows/docs-preview-delete.yml
This adds a workflow to delete a sync branch when a PR in one of the other repos is closed or merged
=> add docs-preview-delete workflow

apps/svelte.dev/content/tutorial/02-advanced-svelte/05-advanced-transitions/02-animations/index.md
This is the fix for the issue #777
=> docs: Fix code typo in `Tutorial: Advanced Svelte Advanced transitions Animations`

packages/editor/src/lib/codemirror.css
=> `.cm-panel` should inherit `color`

packages/repl/src/lib/Output/console/Console.svelte, packages/repl/src/lib/Output/console/ConsoleLine.svelte
closes #792. though honestly i think #523 is probably the right way to go
=> fix console styling

apps/svelte.dev/package.json, apps/svelte.dev/svelte.config.js, pnpm-lock.yaml
I wanted to fix #14168 but didn't get it done in time. But we can't leave the site in its current state. Downgrading Svelte for now
=> downgrade svelte

apps/svelte.dev/package.json, apps/svelte.dev/svelte.config.js, packages/editor/package.json, packages/repl/package.json, packages/site-kit/package.json, pnpm-lock.yaml
=> bump svelte

apps/svelte.dev/package.json, apps/svelte.dev/src/routes/tutorial/[...slug]/+page.server.ts, packages/editor/package.json, packages/repl/package.json, packages/site-kit/package.json, pnpm-lock.yaml
this means that e.g. `/tutorial/kit/` will work
=> fix redirects

apps/svelte.dev/package.json, pnpm-lock.yaml
pairs with https://github.com/sveltejs/kit/pull/13086
=> install @cloudflare/workers-types

apps/svelte.dev/content/blog/2024-12-01-advent-of-svelte.md
see https://discord.com/channels/457912077277855764/1313206079316037694/1313207605908475936
link: https://svelte.dev/playground/untitled?version=5.4.0#H4sIAAAAAAAAA3WP3WrDMAyFX0VoDFqWtGRXxWsKY4-x7MKx1SbUtY2tdi0h7z7s_myD9k6c8-lIZ0Ard4QCPzqKEVong8YC172hiOJzQD75ZCcBiyv87v0sHshw0loZ6Z6unGWyHFHgUvcHUEbGWDeo0qUyX2pw1diGhyeSqoMBDNkNdwIWMBYQpN2OyX4EpJ8uQMO_J0RrpNrWwyQFwEvGpvAMr1DXNVTjajnX_WF1SZ6n5JxyG2--XUY-Gcro7M_bMJyXdR-9kScBm9Drt7OWxpJp541kKpUz-52NAgJ5kjxZFFCtw_QuG9z3I7B1QVMQUPkjRGd6DbnjxZXRk-IySO6dgCqpWZ9l6Ppsw61U201we6vFv_3cPvc-18UCmY6MgsOexq_xBw8BVaUkAgAA
=> fix: replace rows with grid-template-rows to increase browser compat

apps/svelte.dev/src/routes/blog/rss.xml/+server.js
=> prerender RSS feed

apps/svelte.dev/content/tutorial/01-svelte/04-logic/06-await-blocks/+assets/app-a/src/lib/utils.js
This PR makes the comments of the function in the tutorial clearer and more accurate to what the function does.
=> chore: Update comments on utils.js for clarity and accuracy

packages/repl/src/lib/Output/console/ConsoleLine.svelte
renders links as such in console messages (though honestly we should probably just do #523)
=> add links to console output

packages/editor/package.json, packages/repl/package.json, packages/site-kit/package.json, pnpm-lock.yaml
Hopefully fixes #974 
Reverts sveltejs/svelte.dev#947
=> Revert "fix: Update package version of codemirror/view to fix carret low contrast"

apps/svelte.dev/src/routes/e/tmp/codes.json/+server.ts
=> fix: account for section-less pages during code redirects

packages/repl/src/lib/workers/bundler/plugins/commonjs.ts
This brings the CommonJS plugin more in line with the 'real' one — it generates named exports for this common pattern:
```js
exports.foo = foo;
```
With this change, more packages work
=> better commonjs support

apps/svelte.dev/package.json, package.json, packages/editor/package.json, packages/repl/package.json, pnpm-lock.yaml
fixes nine of the issues listed on https://github.com/sveltejs/svelte.dev/security
=> chore: fix some dependabot security warnings

apps/svelte.dev/package.json, apps/svelte.dev/src/routes/tutorial/[...slug]/+page.svelte, packages/repl/package.json, packages/repl/src/lib/Output/Output.svelte, packages/repl/src/lib/Output/PaneWithPanel.svelte, packages/repl/src/lib/Output/Viewer.svelte, packages/repl/src/lib/Repl.svelte, packages/site-kit/src/lib/styles/utils/dividers.css, pnpm-lock.yaml
bumps `svelte-split-pane` in preparation for #1024
=> bump svelte-split-pane

packages/editor/src/lib/Workspace.svelte.ts
=> fix cursor position on state changes

packages/site-kit/src/lib/components/ThemeToggle.svelte
=> fix: prevent FOUC for theme

.github/workflows/docs-preview-create.yml
I think I got wrecked by JSON again
=> chore: Fix broken trailing comma

packages/editor/src/lib/compile-worker/worker.ts, packages/repl/src/lib/workers/bundler/index.ts
move along, nothing to see here
=> support experimental options

package.json
See also https://github.com/sveltejs/svelte/pull/15258 and https://github.com/sveltejs/kit/pull/13442
=> chore: allow running with pnpm 10

.github/workflows/docs-preview-create.yml
=> chore: update workflow permissions again

.github/workflows/sync-docs.yml
maybe this will work maybe it won't
=> chore: fix sync-docs workflow

apps/svelte.dev/content/tutorial/+assets/package.json, apps/svelte.dev/package.json, apps/svelte.dev/scripts/create-tutorial-zip/common/package-lock.json, apps/svelte.dev/scripts/create-tutorial-zip/common/package.json, packages/editor/package.json, packages/repl/package.json, packages/site-kit/package.json, pnpm-lock.yaml
this might be necessary for `getRequestEvent` docs to successfully deploy?
=> chore: bump kit

packages/repl/package.json, packages/site-kit/package.json
we added these in #181 because per #77 it results in 'smaller output'...
...because it's omitting code we need. This will close #1210, but we should see what the impact on bundle size is before committing
=> remove sideEffects: false

apps/svelte.dev/vite.config.ts, packages/editor/src/lib/compile-worker/index.ts, packages/repl/src/lib/Bundler.ts, packages/repl/src/lib/workers/bundler/index.ts, packages/site-kit/src/lib/search/SearchBox.svelte
trying this to see if it results in Tailwind being loaded lazily. fingers crossed...
=> use module workers

packages/repl/src/lib/workers/bundler/index.ts, packages/repl/src/lib/workers/compiler/index.ts
=> fix: better cache, avoid tailwind crashing everything

apps/svelte.dev/content/examples/00-introduction/00-hello-world/+assets/App.svelte
right now if you go to https://svelte.dev/playground the example is pretty lacklustre — it doesn't demonstrate state etc, there's nothing to interact with. I think it would make more sense to have something like this
=> more interesting hello world

apps/svelte.dev/package.json, pnpm-lock.yaml
=> add valibot (needed for remote functions docs)

packages/repl/src/lib/Repl.svelte
It looks like #1518 was merged without checking if the lint test passed, so this should correct it.
=> fix: fix failing lint
